/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.fei.view;

import br.edu.fei.model.Video;
import br.edu.fei.model.dao.CurtirDAO;
import br.edu.fei.model.dao.FavoritosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kamil 
 * tela para favoridos
 */
public class FavoritosJFrame extends javax.swing.JFrame {
    private int usuarioId;//puxa por usuario
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FavoritosJFrame.class.getName());
  
    /**
     * Creates new form FavoritosJFrame
     */
    public FavoritosJFrame() {
        initComponents();//componentes
        setLocationRelativeTo(null); //centraliza
        //apagar a coluna de id
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);
    }
    //set usuario
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
        listarFavoritos();
    }
    
    //config de de lista de favoritos que carrega até a curtida 
    public void listarFavoritos() {

        FavoritosDAO dao = new FavoritosDAO();

        List<Video> lista = dao.listarFavoritos(usuarioId);

        DefaultTableModel modelo =
            (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        CurtirDAO curtidaDAO = new CurtirDAO();

        for (Video video : lista) {

            boolean curtiu = false;

            if (usuarioId > 0) {
                curtiu = curtidaDAO.usuarioCurtiu(usuarioId, video.getId());
            }

            modelo.addRow(new Object[]{
                video.getId(),
                video.getTitulo(),
                video.getDescricao(),
                video.getCategoria(),
                video.getClassificacaoIndicativa(),
                curtiu ? "❤️" : ""
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntIrParaPrincipal = new javax.swing.JButton();
        btnSairFavoritos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bntExcluirListaFavorito = new javax.swing.JButton();
        bntExcluirVideoDaListaFavorito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(91, 91, 88));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 511));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 0, 0));
        jLabel1.setText("feiTv");

        bntIrParaPrincipal.setBackground(new java.awt.Color(241, 0, 0));
        bntIrParaPrincipal.setText("Voltar");
        bntIrParaPrincipal.addActionListener(this::bntIrParaPrincipalActionPerformed);

        btnSairFavoritos.setBackground(new java.awt.Color(241, 0, 0));
        btnSairFavoritos.setText("Sair");
        btnSairFavoritos.addActionListener(this::btnSairFavoritosActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bntIrParaPrincipal)
                .addGap(343, 343, 343)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairFavoritos)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bntIrParaPrincipal)
                    .addComponent(btnSairFavoritos))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Favoritos");

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Descrição", "Categoria", "Classificação", "Curtida"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(1000, 511));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(2);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(2);
            jTable1.getColumnModel().getColumn(1).setMinWidth(200);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(2).setMinWidth(500);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(500);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(500);
            jTable1.getColumnModel().getColumn(3).setMinWidth(90);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(90);
            jTable1.getColumnModel().getColumn(4).setMinWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(5).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        bntExcluirListaFavorito.setBackground(new java.awt.Color(241, 0, 0));
        bntExcluirListaFavorito.setText("Excluir lista");
        bntExcluirListaFavorito.addActionListener(this::bntExcluirListaFavoritoActionPerformed);

        bntExcluirVideoDaListaFavorito.setBackground(new java.awt.Color(241, 0, 0));
        bntExcluirVideoDaListaFavorito.setText("Excluir Video");
        bntExcluirVideoDaListaFavorito.addActionListener(this::bntExcluirVideoDaListaFavoritoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(bntExcluirListaFavorito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntExcluirVideoDaListaFavorito)
                .addGap(200, 200, 200))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntExcluirVideoDaListaFavorito)
                    .addComponent(bntExcluirListaFavorito))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //excluir o video da lista 
    private void bntExcluirVideoDaListaFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirVideoDaListaFavoritoActionPerformed
        int linha = jTable1.getSelectedRow();

            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um vídeo!");
                return;
            }

            int videoId = (int) jTable1.getValueAt(linha, 0);

            FavoritosDAO dao = new FavoritosDAO();
            dao.removerVideo(usuarioId, videoId);

            JOptionPane.showMessageDialog(this, "Removido dos favoritos!");

            listarFavoritos();
    }//GEN-LAST:event_bntExcluirVideoDaListaFavoritoActionPerformed
    //excluir a lista por completo
    private void bntExcluirListaFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirListaFavoritoActionPerformed
         int confirm = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir toda a lista?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {

                FavoritosDAO dao = new FavoritosDAO();
                dao.excluirLista(usuarioId);

                JOptionPane.showMessageDialog(this, "Lista excluída!");

                listarFavoritos();
            }
    }//GEN-LAST:event_bntExcluirListaFavoritoActionPerformed
    //voltar para tela principal
    private void bntIrParaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIrParaPrincipalActionPerformed
        PrincipalJFrame tela = new PrincipalJFrame();

        tela.setUsuarioId(usuarioId);

        tela.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_bntIrParaPrincipalActionPerformed
    //sair do programa
    private void btnSairFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairFavoritosActionPerformed
        LoginJFrame login = new LoginJFrame();

        login.setController(
            new br.edu.fei.controller.LoginController()
        );

        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnSairFavoritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FavoritosJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExcluirListaFavorito;
    private javax.swing.JButton bntExcluirVideoDaListaFavorito;
    private javax.swing.JButton bntIrParaPrincipal;
    private javax.swing.JButton btnSairFavoritos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
