/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.fei.view;

import br.edu.fei.model.Video;
import br.edu.fei.model.dao.VideoDAO;
import br.edu.fei.model.dao.CurtirDAO;
import br.edu.fei.model.dao.FavoritosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author kamil
 * tela principal, a que abre em seguida de login
 */
public class PrincipalJFrame extends javax.swing.JFrame {
    private int usuarioId; //puxa pelo usuario
       //set usuario
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
        listarVideosTela();
    }
    
    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();//componentes
        setLocationRelativeTo(null); //centraliza tela
        //apaga a coluna do ID
        tblVideos.getColumnModel().getColumn(0).setMinWidth(0);
        tblVideos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblVideos.getColumnModel().getColumn(0).setWidth(0);
        //scroller por que o netbeas sumiu com o scroller dessa tabela
        tblVideos.setFillsViewportHeight(true);
        jScrollPane1.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    }
    //lisata do videos e ainda a curtida aparecendo
    public void listarVideosTela() {

        VideoDAO dao = new VideoDAO();
        ArrayList<Video> lista = dao.listarVideos();

        DefaultTableModel modelo =
                (DefaultTableModel) tblVideos.getModel();

        modelo.setRowCount(0);

        CurtirDAO curtidaDAO = new CurtirDAO();

        for (Video video : lista) {

            boolean curtiu = false;

            if (usuarioId > 0) {
                curtiu = curtidaDAO.usuarioCurtiu(usuarioId, video.getId());
            }

            
            modelo.addRow(new Object[]{
                    video.getId(),
                    video.getTitulo(),
                    video.getDescricao(),
                    video.getCategoria(),
                    video.getClassificacaoIndicativa(),
                    curtiu ? "❤️" : ""
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSairPrincipal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarVideo = new javax.swing.JTextField();
        btnBuscarVideo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCurtir = new javax.swing.JButton();
        btnDescurtir = new javax.swing.JButton();
        bntIrParaListaFavoritos = new javax.swing.JButton();
        bntAdicionarFavorito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 511));

        jPanel1.setBackground(new java.awt.Color(91, 91, 88));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 511));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 0, 0));
        jLabel1.setText("feiTv");

        btnSairPrincipal.setBackground(new java.awt.Color(241, 0, 0));
        btnSairPrincipal.setText("Sair");
        btnSairPrincipal.addActionListener(this::btnSairPrincipalActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairPrincipal)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSairPrincipal)
                        .addGap(32, 32, 32))))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bem-Vindo!!");

        tblVideos.setBackground(new java.awt.Color(153, 153, 153));
        tblVideos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tblVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Descrição", "Categoria", "Classificação", "Curtida"
            }
        ));
        tblVideos.setPreferredSize(new java.awt.Dimension(10000, 100000));
        jScrollPane1.setViewportView(tblVideos);
        if (tblVideos.getColumnModel().getColumnCount() > 0) {
            tblVideos.getColumnModel().getColumn(0).setMinWidth(2);
            tblVideos.getColumnModel().getColumn(0).setPreferredWidth(2);
            tblVideos.getColumnModel().getColumn(0).setMaxWidth(2);
            tblVideos.getColumnModel().getColumn(1).setMinWidth(200);
            tblVideos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblVideos.getColumnModel().getColumn(1).setMaxWidth(200);
            tblVideos.getColumnModel().getColumn(2).setMinWidth(500);
            tblVideos.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblVideos.getColumnModel().getColumn(2).setMaxWidth(500);
            tblVideos.getColumnModel().getColumn(3).setMinWidth(90);
            tblVideos.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblVideos.getColumnModel().getColumn(3).setMaxWidth(90);
            tblVideos.getColumnModel().getColumn(4).setMinWidth(80);
            tblVideos.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblVideos.getColumnModel().getColumn(4).setMaxWidth(80);
            tblVideos.getColumnModel().getColumn(5).setMinWidth(50);
            tblVideos.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblVideos.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Video:");

        txtBuscarVideo.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscarVideo.addActionListener(this::txtBuscarVideoActionPerformed);

        btnBuscarVideo.setBackground(new java.awt.Color(241, 0, 0));
        btnBuscarVideo.setText("Buscar");
        btnBuscarVideo.addActionListener(this::btnBuscarVideoActionPerformed);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selecione o video para curtir/descurtir:");

        btnCurtir.setText("Curtir");
        btnCurtir.addActionListener(this::btnCurtirActionPerformed);

        btnDescurtir.setText("Descurtir");
        btnDescurtir.addActionListener(this::btnDescurtirActionPerformed);

        bntIrParaListaFavoritos.setBackground(new java.awt.Color(241, 0, 0));
        bntIrParaListaFavoritos.setText("Lista de Favoritos");
        bntIrParaListaFavoritos.addActionListener(this::bntIrParaListaFavoritosActionPerformed);

        bntAdicionarFavorito.setBackground(new java.awt.Color(241, 0, 0));
        bntAdicionarFavorito.setText("Adicionar Favorito");
        bntAdicionarFavorito.addActionListener(this::bntAdicionarFavoritoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarVideo)
                        .addGap(30, 30, 30)
                        .addComponent(btnBuscarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntIrParaListaFavoritos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCurtir)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnDescurtir)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntAdicionarFavorito)
                                .addGap(186, 186, 186))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscarVideo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCurtir)
                        .addComponent(btnDescurtir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntIrParaListaFavoritos)
                    .addComponent(bntAdicionarFavorito))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //sair do sistema
    private void btnSairPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPrincipalActionPerformed
       LoginJFrame login = new LoginJFrame();

        login.setController(
            new br.edu.fei.controller.LoginController()
        );

        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnSairPrincipalActionPerformed
     //buscar o video
    private void btnBuscarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVideoActionPerformed
        String titulo = txtBuscarVideo.getText();

        VideoDAO dao = new VideoDAO();
        ArrayList<Video> lista = dao.buscarVideosPorNome(titulo);

        DefaultTableModel modelo =
                (DefaultTableModel) tblVideos.getModel();

        modelo.setRowCount(0);

        CurtirDAO curtidaDAO = new CurtirDAO();

        for (Video video : lista) {

            boolean curtiu = false;

            if (usuarioId > 0) {
                curtiu = curtidaDAO.usuarioCurtiu(usuarioId, video.getId());
            }
            
            

            modelo.addRow(new Object[]{
                    video.getId(),
                    video.getTitulo(),
                    video.getDescricao(),
                    video.getCategoria(),
                    video.getClassificacaoIndicativa(),
                    curtiu ? "❤️" : ""
                });
        }
    }//GEN-LAST:event_btnBuscarVideoActionPerformed
    //curtir o video
    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        int linha = tblVideos.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um vídeo!");
            return;
        }

        int videoId = (int) tblVideos.getValueAt(linha, 0);

        CurtirDAO dao = new CurtirDAO();
        dao.curtirVideo(usuarioId, videoId);

        listarVideosTela();
    }//GEN-LAST:event_btnCurtirActionPerformed
    //descurtir o video
    private void btnDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescurtirActionPerformed
        int linha = tblVideos.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um vídeo!");
            return;
        }

        int videoId = (int) tblVideos.getValueAt(linha, 0);

        CurtirDAO dao = new CurtirDAO();
        dao.descurtirVideo(usuarioId, videoId);

        listarVideosTela();
    }//GEN-LAST:event_btnDescurtirActionPerformed
    //ir para favoritos se existir a lista
    private void bntIrParaListaFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIrParaListaFavoritosActionPerformed
        if (usuarioId <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Usuário inválido. Faça login novamente."
            );

            return;
        }
        
        FavoritosDAO dao = new FavoritosDAO();

        System.out.println(dao.existeLista(usuarioId));
        
        if (!dao.existeLista(usuarioId)) {

            JOptionPane.showMessageDialog(this,
                    "Você ainda não possui lista de favoritos."
                + "Adicione um vídeo para criar sua lista.");
                return;
        }

        FavoritosJFrame tela = new FavoritosJFrame();

        tela.setUsuarioId(usuarioId);

        tela.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_bntIrParaListaFavoritosActionPerformed
    //adiciona o video a favoritos para criar a lista de favoridos
    private void bntAdicionarFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarFavoritoActionPerformed
        int linha = tblVideos.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um vídeo!");
            return;
        }

        int videoId = (int) tblVideos.getValueAt(linha, 0);

        if (usuarioId <= 0) {
            JOptionPane.showMessageDialog(this, "Usuário inválido!");
            return;
        }

        FavoritosDAO dao = new FavoritosDAO();

        if (!dao.existeLista(usuarioId)) {

            dao.criarLista(usuarioId);
        }
        
        List<Video> favoritos = dao.listarFavoritos(usuarioId);

        for (Video video : favoritos) {
            if (video.getId() == videoId) {
                JOptionPane.showMessageDialog(this, "Esse vídeo já está nos favoritos!");
                return;
            }
        }
        
        
        dao.adicionarVideo(usuarioId, videoId);

        JOptionPane.showMessageDialog(this, "Adicionado aos favoritos!");

        listarVideosTela();
    }//GEN-LAST:event_bntAdicionarFavoritoActionPerformed

    private void txtBuscarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        java.awt.EventQueue.invokeLater(() -> {
        PrincipalJFrame tela = new PrincipalJFrame();
        
        //nao
        tela.setVisible(true);
        });
        /* Create and display the form */    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionarFavorito;
    private javax.swing.JButton bntIrParaListaFavoritos;
    private javax.swing.JButton btnBuscarVideo;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnDescurtir;
    private javax.swing.JButton btnSairPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVideos;
    private javax.swing.JTextField txtBuscarVideo;
    // End of variables declaration//GEN-END:variables
}
